spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:\C:\Users\USER\Documents\IntelliJProjects\todo-app\todo-db'
  jpa:
    hibernate:
      ddl-auto: validate